### ISSUE TITLE
django-rest-swagger Error

### ISSUE THREAD

**Issue by paras06** [hoangddt/simple-Django-REST-API#2]
Hi,

I am receiving below error when executed the command in Pycharm IDE - **pip install django-rest-swagger**

Please let me to resolve it. Thanks
P

Here is the log data - 
----------------------------------

C:\Project\simple-Django-REST-API>pip install django-rest-swagger
Collecting django-rest-swagger
  Using cached https://files.pythonhosted.org/packages/26/b0/1df8743c3150630c2ce1f98f9f0f451038e43fb58a68d5da7877754f37b7/django_rest_swagger-2.2.0-py2.py3-none-any.whl
Collecting simplejson (from django-rest-swagger)
  Using cached https://files.pythonhosted.org/packages/e3/24/c35fb1c1c315fc0fffe61ea00d3f88e85469004713dab488dee4f35b0aff/simplejson-3.16.0.tar.gz
Requirement already satisfied: coreapi>=2.3.0 in c:\users\xxxxx\appdata\local\programs\python\python37-32\lib\site-packages (from django-rest-swagger) (2.3.3)
Requirement already satisfied: openapi-codec>=1.3.1 in c:\users\xxxxx\appdata\local\programs\python\python37-32\lib\site-packages (from django-rest-swagger) (1.3.2)
Requirement already satisfied: djangorestframework>=3.5.4 in c:\users\xxxxx\appdata\local\programs\python\python37-32\lib\site-packages (from django-rest-swagger) (3.9.0)
Requirement already satisfied: uritemplate in c:\users\xxxxx\appdata\local\programs\python\python37-32\lib\site-packages (from coreapi>=2.3.0->django-rest-swagger) (3.0.0)
Requirement already satisfied: coreschema in c:\users\xxxxx\appdata\local\programs\python\python37-32\lib\site-packages (from coreapi>=2.3.0->django-rest-swagger) (0.0.4)
Requirement already satisfied: requests in c:\users\xxxxx\appdata\local\programs\python\python37-32\lib\site-packages (from coreapi>=2.3.0->django-rest-swagger) (2.21.0)
Requirement already satisfied: itypes in c:\users\xxxxx\appdata\local\programs\python\python37-32\lib\site-packages (from coreapi>=2.3.0->django-rest-swagger) (1.1.0)
Requirement already satisfied: jinja2 in c:\users\xxxxx\appdata\local\programs\python\python37-32\lib\site-packages (from coreschema->coreapi>=2.3.0->django-rest-swagger) (2.10)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\users\xxxxx\appdata\local\programs\python\python37-32\lib\site-packages (from requests->coreapi>=2.3.0->django-rest-swagger) (3.0.4)
Requirement already satisfied: urllib3<1.25,>=1.21.1 in c:\users\xxxxx\appdata\local\programs\python\python37-32\lib\site-packages (from requests->coreapi>=2.3.0->django-rest-swagger) (1.24.1)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\xxxxx\appdata\local\programs\python\python37-32\lib\site-packages (from requests->coreapi>=2.3.0->django-rest-swagger) (2018.10.15)
Requirement already satisfied: idna<2.9,>=2.5 in c:\users\xxxxx\appdata\local\programs\python\python37-32\lib\site-packages (from requests->coreapi>=2.3.0->django-rest-swagger) (2.7)
Requirement already satisfied: MarkupSafe>=0.23 in c:\users\xxxxx\appdata\local\programs\python\python37-32\lib\site-packages (from jinja2->coreschema->coreapi>=2.3.0->django-rest-swagger) (1.1.0)
Installing collected packages: simplejson, django-rest-swagger
  Running setup.py install for simplejson ... error
    Complete output from command c:\users\xxxxx\appdata\local\programs\python\python37-32\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\xxxxx\\AppData\\Local\\Temp\\pip-install-g2_1wqeu\\simplejson\\setup.py';f=getattr(tokenize, 'open', open
)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\xxxxx\AppData\Local\Temp\pip-record-zn9dnevq\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build\lib.win32-3.7
    creating build\lib.win32-3.7\simplejson
    copying simplejson\compat.py -> build\lib.win32-3.7\simplejson
    copying simplejson\decoder.py -> build\lib.win32-3.7\simplejson
    copying simplejson\encoder.py -> build\lib.win32-3.7\simplejson
    copying simplejson\errors.py -> build\lib.win32-3.7\simplejson
    copying simplejson\ordered_dict.py -> build\lib.win32-3.7\simplejson
    copying simplejson\raw_json.py -> build\lib.win32-3.7\simplejson
    copying simplejson\scanner.py -> build\lib.win32-3.7\simplejson
    copying simplejson\tool.py -> build\lib.win32-3.7\simplejson
    copying simplejson\__init__.py -> build\lib.win32-3.7\simplejson
    creating build\lib.win32-3.7\simplejson\tests
    copying simplejson\tests\test_bigint_as_string.py -> build\lib.win32-3.7\simplejson\tests
    copying simplejson\tests\test_bitsize_int_as_string.py -> build\lib.win32-3.7\simplejson\tests
    copying simplejson\tests\test_check_circular.py -> build\lib.win32-3.7\simplejson\tests
    copying simplejson\tests\test_decimal.py -> build\lib.win32-3.7\simplejson\tests
    copying simplejson\tests\test_decode.py -> build\lib.win32-3.7\simplejson\tests
    copying simplejson\tests\test_default.py -> build\lib.win32-3.7\simplejson\tests
    copying simplejson\tests\test_dump.py -> build\lib.win32-3.7\simplejson\tests
    copying simplejson\tests\test_encode_basestring_ascii.py -> build\lib.win32-3.7\simplejson\tests
    copying simplejson\tests\test_encode_for_html.py -> build\lib.win32-3.7\simplejson\tests
    copying simplejson\tests\test_errors.py -> build\lib.win32-3.7\simplejson\tests
    copying simplejson\tests\test_fail.py -> build\lib.win32-3.7\simplejson\tests
    copying simplejson\tests\test_float.py -> build\lib.win32-3.7\simplejson\tests
    copying simplejson\tests\test_for_json.py -> build\lib.win32-3.7\simplejson\tests
    copying simplejson\tests\test_indent.py -> build\lib.win32-3.7\simplejson\tests
    copying simplejson\tests\test_item_sort_key.py -> build\lib.win32-3.7\simplejson\tests
    copying simplejson\tests\test_iterable.py -> build\lib.win32-3.7\simplejson\tests
    copying simplejson\tests\test_namedtuple.py -> build\lib.win32-3.7\simplejson\tests
    copying simplejson\tests\test_pass1.py -> build\lib.win32-3.7\simplejson\tests
    copying simplejson\tests\test_pass2.py -> build\lib.win32-3.7\simplejson\tests
    copying simplejson\tests\test_pass3.py -> build\lib.win32-3.7\simplejson\tests
    copying simplejson\tests\test_raw_json.py -> build\lib.win32-3.7\simplejson\tests
    copying simplejson\tests\test_recursion.py -> build\lib.win32-3.7\simplejson\tests
    copying simplejson\tests\test_scanstring.py -> build\lib.win32-3.7\simplejson\tests
    copying simplejson\tests\test_separators.py -> build\lib.win32-3.7\simplejson\tests
    copying simplejson\tests\test_speedups.py -> build\lib.win32-3.7\simplejson\tests
    copying simplejson\tests\test_str_subclass.py -> build\lib.win32-3.7\simplejson\tests
    copying simplejson\tests\test_subclass.py -> build\lib.win32-3.7\simplejson\tests
    copying simplejson\tests\test_tool.py -> build\lib.win32-3.7\simplejson\tests
    copying simplejson\tests\test_tuple.py -> build\lib.win32-3.7\simplejson\tests
    copying simplejson\tests\test_unicode.py -> build\lib.win32-3.7\simplejson\tests
    copying simplejson\tests\__init__.py -> build\lib.win32-3.7\simplejson\tests
    running build_ext
    building 'simplejson._speedups' extension
    error: [WinError 3] The system cannot find the path specified: 'C:\\Program Files (x86)\\Microsoft SDKs\\Windows\\v8.1\\lib'

    ----------------------------------------
Command "c:\users\xxxxx\appdata\local\programs\python\python37-32\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\xxxxx\\AppData\\Local\\Temp\\pip-install-g2_1wqeu\\simplejson\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read(
).replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\xxxxx\AppData\Local\Temp\pip-record-zn9dnevq\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\xxxxx\AppData\L
ocal\Temp\pip-install-g2_1wqeu\simplejson\

**Comment by hoangddt** [comment]
Hi there, your output says:
`error: [WinError 3] The system cannot find the path specified: 'C:\Program Files (x86)\Microsoft SDKs\Windows\v8.1\lib'`.

It might be a problem with Windows SDK. Please make sure the path: `'C:\Program Files (x86)\Microsoft SDKs\Windows\v8.1\lib` is exist on your system. If not, download and install Windows SDK and try again.

**Comment by paras06** [comment]
Hi, after re-installation of Windows SDK, the above issue got resolved. 

Thanks for your quick response.

**Comment by hoangddt** [comment]
You're welcome, glad that you fixed it. Happy coding
